sudo: false
language: go
go:
  - 1.9

install:
  - go get
  - go get github.com/mitchellh/gox

script:
  - gox -arch="amd64" -os="darwin linux windows" -output "dist/{{.OS}}-{{.Arch}}/{{.Dir}}" .
  - zip -j sts-profile-${TRAVIS_TAG}-darwin-amd64.zip ./dist/darwin-amd64/*
  - zip -j sts-profile-${TRAVIS_TAG}-linux-amd64.zip ./dist/linux-amd64/*
  - zip -j sts-profile-${TRAVIS_TAG}-windows-amd64.zip ./dist/windows-amd64/*

deploy:
  provider: releases
  api_key:
    secure: g3qc91yv3REAmFIGswmWfbyERsqac6uS8daQdNVGTBrMjKhfyHHfQsIh4+AKHiaXsHjJLp5iLS9zGJYcrPN5wAhh3plOv4xSzV9epuO/q+5fnRnPrrdo14ScPHrctcxceocNjl8gvqTQsSh7an51JhhH/A5AK9miapuceL5q46i5b3zRguxeizbsbEj3uAv3vJHGRvkyJ/xCPdqbx1YO5AMZPm1cDdYJTA7SdGgHQisSF06dm4hHiAREknXSklivw7sxgvkmeHMRGBcFEovWmMHNmu4noQO4NygiZjk2GB6dHp6jScY5Xf1qfDGeB6yPbyciKoB0T6SEm9mQ4p60ViwQDax1LorKMyrp7U4gM3ZCV3ty40kBgcm/muya5+BA5ioBz4996DHIYkYH3RBNCRNkTjIvujSGO3Tud/988WmBBaquCDWBOsPeC7nCBlRTelRqv3R27YwAiVZB+E9EXJLDz5sCwb1ZeC93SXy3xIrBIXzssGAXo4qcxOiglYyvqOqBTMmMjsmLOH8ZQOW/HDr9QrkPx0J+RWKTvpLcKbIfkg12H4dJv8TNbLlQkAsnc6mWtg5QtB61LfJMLxCnRfZLrIu8aAMdvomH2BaMkxJ01z3kmbvxb0yiOLZc23x0wiDlYVtNwVpfnITfFP8gO31oU8YQSjeEtJmBXNQrGpw=
  file:
    - sts-profile-${TRAVIS_TAG}-darwin-amd64.zip
    - sts-profile-${TRAVIS_TAG}-linux-amd64.zip
    - sts-profile-${TRAVIS_TAG}-windows-amd64.zip
  on:
    repo: Jalle19/sts-profile
    tags: true
